### PR TITLE
Efficient Realtime Sync

### LINKED ISSUE #228: [Feature] Alternative realtime sync strategy for fast chains
The new realtime indexing strategy calls `eth_getBlockByNumber` for every new block on the chain. This works just fine for the majority of chains that have a block time >=2 seconds. But, this approach does not work well for chains like Arbitrum that have a very short block time (Arbitrum targets 0.25 seconds). The reorg-safe approach also (generally) consumes more RPC usage.

It likely makes sense to offer two approaches:
1. **Reorg safe**. This is the approach currently used in main. In a nutshell, it fetches every block using `eth_getBlockByNumber`, checks if any of the registered log filters match `block.logsBloom`. If yes, call `eth_getLogs`, add the matched logs, transactions, and block to the store, then process the now-ready events.
2. **Reorg unsafe, RPC-usage optimized**. Ponder previously used this approach. On an interval, fetch the latest block, then call `eth_getLogs` from the previous latest block number to the new one. This could be further optimized by only calling `eth_getLogs` with `fromBlock` equal to some known-to-be-handled block number in the past and `toBlock: "latest"`, then de-duping any repeated events.

Approach 2 would be appropriate for any chains where it is reasonable to assume that there will never be a reorg (which, AFAIK, includes Arbitrum).

This option could be exposed to the user as a field in `networks` in `ponder.config.ts`.

EDIT: See also #506 for an additional request on this.

### PR DESCRIPTION
**Pull request by kyscott18**
Refactor realtime sync service to use less rpc credits under all scenarios.

Closes #228.

### CODE REVIEW

File: packages/core/src/sync-realtime/service.ts [hunk 1]
```diff
@@ -79,19 +94,48 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
-    let latestBlock: BlockWithTransactions;
+    let latestBlock: RealtimeBlock;
+    let finalizedBlock: RealtimeBlock;
     let rpcChainId: number;
     try {
-      [latestBlock, rpcChainId] = await Promise.all([
-        this.getLatestBlock(),
+      [latestBlock, finalizedBlock, rpcChainId] = await Promise.all([
+        this._eth_getBlockByNumber("latest"),
+        this._eth_getBlockByNumber("finalized"),
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:138]: Not all networks support this, and I suspect the behavior might be inconsistent across providers (some might error, others might return `"latest"` instead, etc.

We could still consider using it if we think there's a real benefit, but would need to handle these cases and fall back to the old behavior.

File: packages/core/src/sync-realtime/service.ts [hunk 2]
```diff
@@ -150,50 +193,24 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
-    // If the latest block was not added to the queue, setup was not completed successfully.
-    if (this.queue.size === 0) {
-      throw new Error(
-        "Unable to start. Must call setup() method before start().",
-      );
+      return;
     }
 
-    // Fetch the block at the finalized block number.
-    const finalizedBlock = await this.requestQueue.request({
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:172]: Lol, made no sense to fetch latest in `setup` and finalized in `start`.

File: packages/core/src/sync-realtime/service.ts [hunk 3]
```diff
@@ -202,444 +219,506 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
+    if (sync === "traverse") await this.syncTraverse(newBlock);
+    else await this.syncBatch(newBlock);
+
+    // If this block moves the finality checkpoint, remove now-finalized blocks from the local chain
+    // and mark data as cached in the store.
     if (
-      newBlock.number === previousHeadBlock.number + 1 &&
-      newBlock.parentHash === previousHeadBlock.hash
+      hexToNumber(newBlock.number) >
+      this.finalizedBlockNumber + 2 * this.network.finalityBlockCount
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:280]: If we do choose to use the `"finalized"` tag, the `finalityBlockCount` logic would also need to be dynamic (I think).

File: packages/core/src/sync-realtime/service.ts [hunk 4]
```diff
@@ -202,444 +219,506 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
 
-        matchedLogs = filterLogs({
-          logs,
-          logFilters: [
-            ...this.sources.filter(sourceIsLogFilter).map((l) => l.criteria),
-            ...factoryLogFilters,
-          ],
-        });
-      }
+    if (costBatch > costTraverse) return "traverse";
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:357]: Might call these `batchCost` and `traverseCost`

File: packages/core/src/sync-realtime/service.ts [hunk 5]
```diff
@@ -202,444 +219,506 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
+    else return "batch";
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:358]: Ternary?

File: packages/core/src/sync-realtime/service.ts [hunk 6]
```diff
@@ -202,444 +219,506 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
-        }
-      } else {
-        // The app has factory contracts.
-        // Don't attempt to skip calling eth_getLogs, just call it every time.
-        logs = await this.requestQueue.request({
-          method: "eth_getLogs",
-          params: [{ blockHash: newBlock.hash }],
-        });
+    // Probability of a log in a block
+    const pLog = Math.min(this.lastLogsPerBlock, 1);
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:349]: Ohhh now he's cooking

File: packages/core/src/sync-realtime/service.ts [hunk 7]
```diff
@@ -202,444 +219,506 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
-            }
-            return {
-              address: childContractAddresses,
-              topics: factory.criteria.topics,
-            };
-          }),
-        );
+    // Probability of no logs in the range of blocks
+    const pNoLogs = (1 - pLog) ** numBlocks;
+    const costTraverse = 16 * numBlocks + 75 * (1 - pNoLogs);
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:355]: Is this double negation intentional?

File: packages/core/src/sync-realtime/service.ts [hunk 8]
```diff
@@ -202,444 +219,506 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
-      if (matchedLogCount > 0) {
-        // Filter transactions down to those that are required by the matched logs.
-        const requiredTransactionHashes = new Set(
-          matchedLogs.map((l) => l.transactionHash),
-        );
-        const filteredTransactions =
-          newBlockWithTransactions.transactions.filter((t) =>
-            requiredTransactionHashes.has(t.hash),
+      if (newBlocks[0].parentHash !== this.mostRecentBlock.hash) {
+        await this.reorgTraverse(newBlocks[0], hexToNumber(newBlock.number));
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:376]: Do you need to return here after this?

File: packages/core/src/sync-realtime/service.ts [hunk 9]
```diff
@@ -202,444 +219,506 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
 
-        // TODO: Maybe rename or at least document behavior
-        await this.syncStore.insertRealtimeBlock({
-          chainId: this.network.chainId,
-          block: newBlockWithTransactions,
-          transactions: filteredTransactions,
-          logs: matchedLogs,
+      if (requestLogs) {
+        // Get logs
+        const logs = await this._eth_getLogs({
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:393]: This is awesome!

File: packages/core/src/sync-realtime/service.ts [hunk 10]
```diff
@@ -202,444 +219,506 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
-          const block = await this.requestQueue.request({
-            method: "eth_getBlockByNumber",
-            params: [numberToHex(number), true],
-          });
-          if (!block) {
-            throw new Error(`Failed to fetch block number: ${number}`);
-          }
-          return block as BlockWithTransactions;
-        });
+    this.mostRecentBlock = realtimeBlockToLightBlock(newBlock);
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:473]: Any reason not to call this `latestBlock`?

File: packages/core/src/sync-realtime/service.ts [hunk 11]
```diff
@@ -202,444 +219,506 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
+    newBlock: RealtimeBlock,
+    latestBlockNumber: number,
+  ) => {
+    const commonAncestor = this.blocks.findLast(
+      (parent) => parent.hash === newBlock.parentHash,
+    );
+
+    if (commonAncestor !== undefined) {
+      // Found parent block in local blocks
+      this.emit("shallowReorg", {
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:489]: I think this should only be emitted after all the store operations are done

File: packages/core/src/sync-realtime/service.ts [hunk 12]
```diff
@@ -202,444 +219,506 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
-      detectedAtBlockNumber: newBlock.number,
-      minimumDepth: depth,
-    });
-
-    this.common.logger.warn({
-      service: "realtime",
-      msg: `Unable to reconcile >${depth}-block reorg (network=${this.network.name})`,
-    });
+  /** Returns true if "blocks" is not missing any blocks from tip to "finalizedBlockNumber". */
+  private isBlocksComplete = (): boolean => {
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:717]: `isLocalChainConsistent` or something similar? Was not sure what this meant when reading it above.

**Review by 0xOlias — COMMENTED** [review]
This looks great, makes a ton of sense. Mostly nits and questions!

File: packages/core/src/sync-realtime/service.ts (hunk 7 above)
Comment (kyscott18) [reply packages/core/src/sync-realtime/service.ts:355]: yes

File: packages/core/src/sync-realtime/service.ts (hunk 8 above)
Comment (kyscott18) [reply packages/core/src/sync-realtime/service.ts:376]: Haven't figured it out yet, not sure you do because right above you just fetched a bunch of new blocks and they might still be useful.

File: packages/core/src/sync-realtime/service.ts (hunk 10 above)
Comment (kyscott18) [reply packages/core/src/sync-realtime/service.ts:473]: At first it was confusing because there was also a function called "getLatestBlock". But now I think it makes sense.

File: packages/core/src/sync-realtime/service.ts (hunk 12 above)
Comment (kyscott18) [reply packages/core/src/sync-realtime/service.ts:717]: Yeah this is a way better name

**Review by 0xOlias — COMMENTED** [review]
Questions and nits

File: packages/core/src/sync-realtime/service.ts [hunk 13]
```diff
@@ -79,19 +92,47 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
+
+    const isAddressDefined = this.logFilterSources.every(
+      (source) => !!source.criteria.address,
+    );
+    this.address =
+      !this.hasFactorySource && isAddressDefined
+        ? (sources.flatMap((source) => source.criteria.address) as Address[])
+        : undefined;
+
+    this.topics = sources.flatMap((source) => {
```
[the remark this answers is not in the document]
Comment (kyscott18) [reply packages/core/src/sync-realtime/service.ts:107]: I'm worried that requesting a range of blocks with no log filters or addresses is going to be over the maximum data size for some rpc providers

File: packages/core/src/sync-realtime/service.ts [hunk 14]
```diff
@@ -150,496 +190,511 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
-        this.common.logger.info({
-          service: "realtime",
-          msg: `Reconciled ${depth}-block reorg with common ancestor block ${commonAncestorBlock.number} (network=${this.network.name})`,
+          blockNumber: commonAncestor.number,
         });
+      }
+    };
 
+    let i = 0;
+    for (; i < localLogs.length && i < matchedLogs.length; i++) {
```
[the remark this answers is not in the document]
Comment (kyscott18) [reply packages/core/src/sync-realtime/service.ts:543]: No, its used after the for loops goes out of scope

File: packages/core/src/sync-realtime/service.ts [hunk 15]
```diff
@@ -150,496 +190,511 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
-
-        // Default to a retry (uses the retry options passed to the queue).
-        queue.addTask({ ...task });
-      },
-    });
-
-    return queue;
+      if (this.isProcessBlockQueued) {
+        this.isProcessBlockQueued = false;
+        await this.processBlock();
```
[the remark this answers is not in the document]
Comment (kyscott18) [reply packages/core/src/sync-realtime/service.ts:263]: There are three cases for the realtime sync process. 

1. Nothing is running.
2. Something is running and after it should wait for the next polling interval.
3. Something is running and before it finished, the polling interval finished. We shouldn't run two at once. The running process should finish and then immediately re-run.

File: packages/core/src/sync-realtime/service.ts [hunk 16]
```diff
@@ -150,496 +190,511 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
+    // Don't attempt to skip "eth_getLogs" if a factory source is present.
+    // Note: this may not be a possible path depending on the implementation of "determineSyncPath".
+    const requestLogs = this.hasFactorySource
+      ? true
+      : newBlocks.some((block) =>
+          isMatchedLogInBloomFilter({
+            bloom: block.logsBloom,
+            logFilters: criteria,
+          }),
+        );
```
[the remark this answers is not in the document]
Comment (kyscott18) [reply packages/core/src/sync-realtime/service.ts:432]: Just making sure this should actually be:

```ts
const canSkipGetLogs =
  !this.hasFactorySource &&
  newBlocks.every((block) =>
    !isMatchedLogInBloomFilter({
      bloom: block.logsBloom,
      logFilters: criteria,
    }))
```

File: packages/core/src/sync-realtime/service.ts [hunk 17]
```diff
@@ -150,496 +190,511 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
+    const logs = await this._eth_getLogs({
+      fromBlock: numberToHex(latestBlockNumber + 1),
+      toBlock: numberToHex(newBlockNumber),
+    });
 
-    // Store the block objects as we fetch them.
-    // Once we find the common ancestor, we will add these blocks to the queue.
-    const canonicalBlocksWithTransactions = [newBlockWithTransactions];
+    const matchedLogs = await this.getMatchedLogs(
+      logs,
```
[the remark this answers is not in the document]
Comment (kyscott18) [reply packages/core/src/sync-realtime/service.ts:468]: Doesn't the call to `eth_getLogs` with endBlock being newBlock do that?

```ts
const logs = await this._eth_getLogs({
  fromBlock: numberToHex(latestLocalBlockNumber + 1),
  toBlock: newBlock.number,
});
```

[the remark this answers is not in the document]
Comment (0xOlias) [reply packages/core/src/sync-realtime/service.ts:488]: Yes, that makes sense

File: packages/core/src/sync-realtime/service.ts [hunk 18]
```diff
@@ -486,160 +374,393 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
+          blockNumber: commonAncestor.number,
         });
+      }
+    };
+
+    let i = 0;
+    for (; i < localLogs.length && i < matchedLogs.length; i++) {
+      const lightMatchedLog = realtimeLogToLightLog(matchedLogs[i]);
+      if (lightMatchedLog.blockHash !== localLogs[i].blockHash) {
+        handleReorg(i);
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:584]: If our local chain has multiple now-invalid blocks, won't this run multiple times (unnecessarily)?

File: packages/core/src/sync-realtime/service.ts [hunk 19]
```diff
@@ -486,160 +374,393 @@ export class RealtimeSyncService extends Emittery<RealtimeSyncEvents> {
...
+
+    return { blocks: blocks, logs: matchedLogs };
+  };
+
+  /**
+   * Check if a re-org occurred by comparing remote logs to local.
+   *
+   * @returns True if a re-org has occurred.
+   */
+  detectReorg = async (latestBlockNumber: number) => {
```
Comment (0xOlias) [inline packages/core/src/sync-realtime/service.ts:511]: Still makes sense to me that this would be called `reconcileReorg` or something. The current function signature kinda suggests to me that it's a pure function.

**Review by 0xOlias — APPROVED** [review]

File: packages/core/src/sync-realtime/service.ts (hunk 18 above)
Comment (kyscott18) [reply packages/core/src/sync-realtime/service.ts:584]: Doesn't it return right after this line?
