### PR TITLE
fix: null bytes

### LINKED ISSUE #1378: bug: null characters throw error when inserted into `text` columns
### Related

https://github.com/ponder-sh/ponder/issues/1376

### Version

0.8.8, 0.7.17

### Current behavior

The server crashes the error (or a similar error for ASCII encoding):
```
FlushError: invalid byte sequence for encoding "UTF8": 0x00
```

### Expected behavior

Flush succeeds regardless of null characters

### Steps to reproduce

Don't have a repro handy, but in general this occurs because EVM `string` values can contain null characters, but the Postgres `text` data type does not allow them. We've seen null characters in decoded event `data` (very likely the source of the user reports we're seeing) as well as raw RPC fields like `trace.revertReason`.

### Link to repository

_No response_

### Anything else?

Two possible solutions:
1. Ensure that any values within the `event` object, particularly decoded event arguments (e.g. `event.args.{xxx}`), do not contain null characters by sanitizing them with `str.replace(/\0/g, '')`.
2. Sanitize any value being inserted into a `text` column at the driver level.

I prefer 1, at least as a starting point. On the raw RPC side of things, we should probably sanitize specific free text fields like revertReason before insertion.

### PR DESCRIPTION
**Pull request by typedarray**
It's possible for decoded values for `string` ABI parameters to contain null characters. Null characters are ignored by almost all software systems, except the postgres `TEXT` data type does not accept them ([context](https://www.commandprompt.com/blog/null-characters-workarounds-arent-good-enough)).

This PR removes null characters from all decoded ABI strings.

Fixes #1378 #1376

### CODE REVIEW

File: packages/core/src/sync/events.ts [hunk 1]
```diff
@@ -500,7 +500,7 @@ export const decodeEvents = (
 
                 event: {
                   name: safeName,
-                  args,
+                  args: removeNullCharacters(args),
```
Comment (typedarray) [inline packages/core/src/sync/events.ts:503]: @kyscott18 lmk if this is the correct place to do this - both historical and realtime events pass through this, yes?

Comment (kyscott18) [reply packages/core/src/sync/events.ts:503]: Yes

**Review by kyscott18 — APPROVED** [review]
