### PR TITLE
validate JSON-RPC response INTEGER and BIGINT size

### LINKED ISSUE #2103: out of range for type integer for custom event example
### Version

0.13.13

### Current behavior

5:31:26 PM WARN  database   Failed 'insert_logs' database query after '10' attempts (id=813245e7)
error: value "4294967295" is out of range for type integer
    at he.Fe (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pg-protocol/src/parser.ts:432:11)
    at he.rt (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pg-protocol/src/parser.ts:210:16)
    at he.__privateGet [as parse] (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pg-protocol/src/parser.ts:102:25)
    at te.execProtocol (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pglite/src/pglite.ts:609:5)
    at te.o (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pglite/src/base.ts:130:12)
    at file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pglite/src/base.ts:245:13
where: unnamed portal parameter $27 = '...'
5:31:26 PM ERROR sync       Fatal error: Unable to sync 'mainnet' from 14517920 to 14597008.
error: value "4294967295" is out of range for type integer
    at he.Fe (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pg-protocol/src/parser.ts:432:11)
    at he.rt (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pg-protocol/src/parser.ts:210:16)
    at he.__privateGet [as parse] (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pg-protocol/src/parser.ts:102:25)
    at te.execProtocol (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pglite/src/pglite.ts:609:5)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at te.o (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pglite/src/base.ts:130:12)
    at file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pglite/src/base.ts:245:13
where: unnamed portal parameter $27 = '...'
5:31:26 PM ERROR process    Caught unhandledRejection event
error: value "4294967295" is out of range for type integer
    at he.Fe (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pg-protocol/src/parser.ts:432:11)
    at he.rt (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pg-protocol/src/parser.ts:210:16)
    at he.__privateGet [as parse] (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pg-protocol/src/parser.ts:102:25)
    at te.execProtocol (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pglite/src/pglite.ts:609:5)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at te.o (file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pglite/src/base.ts:130:12)
    at file:///Volumes/Data/codes/obscure/leagues-eth-indexer/node_modules/.pnpm/@electric-sql+pglite@0.2.13/node_modules/@electric-sql/pglite/src/base.ts:245:13
where: unnamed portal parameter $27 = '...'
5:31:26 PM WARN  process    Received fatal error, starting shutdown sequence

### Expected behavior

it should index properly and might throw 429 but should not crash

### Steps to reproduce

create a new project with  Custom event filter and run the dev server

### Link to repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kyscott18**
Closes #2103

### CODE REVIEW

File: packages/core/src/rpc/actions.ts [hunk 1]
```diff
@@ -924,6 +935,22 @@ export const standardizeTransaction = (
     transaction.gas = "0x0";
   }
 
+  if (hexToBigInt(transaction.blockNumber) > PG_BIGINT_MAX) {
+    throw new Error(
+      "'transaction.blockNumber' is larger than the maximum allowed value",
```
Comment (typedarray) [inline packages/core/src/rpc/actions.ts]: Invalid RPC response: 'transaction.blockNumber' (${hexToBigInt(transaction.blockNumber)}) is larger than the maximum allowed value (${PG_BIGINT_MAX}). Please try a different RPC and report this to the chain or RPC provider.`
