### PR TITLE
use COPY statement for flush

### LINKED ISSUE #1469: Error Flushing Cash
### Version

0.8.32

### Current behavior

Got this error, and it said to report it. 

7:34:00 PM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
7:34:00 PM WARN  user       Failed 'token_flow.flush()' database method (id=4a98a881)
FlushError: canceling statement due to statement timeout
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:860:31
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:846:21
    at HeadlessKysely.wrap (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/database/kysely.ts:58:24)
    at async Promise.all (index 21)
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:869:9
    at Object.flush (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:754:7)
    at start2 (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/bin/utils/run.ts:210:9)

7:34:00 PM ERROR process    Caught unhandledRejection event
FlushError: canceling statement due to statement timeout
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/common/src/queue.ts:184:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.flush (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:754:7)
    at start2 (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/bin/utils/run.ts:210:9)

7:34:00 PM WARN  process    Received unhandledRejection, starting shutdown sequence
7:34:00 PM ERROR process    Caught unhandledRejection event
FlushError: canceling statement due to statement timeout
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/common/src/queue.ts:184:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.flush (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:754:7)
    at start2 (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/bin/utils/run.ts:210:9)

(node:13602) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 7814447)
(Use `node --trace-warnings ...` to show where the warning was created)
7:34:00 PM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
7:34:00 PM WARN  user       Failed 'flow_path.flush()' database method (id=3cdae79b)
FlushError: canceling statement due to statement timeout
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:813:31
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:804:21
    at HeadlessKysely.wrap (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/database/kysely.ts:58:24)
    at async Promise.all (index 29)

7:34:00 PM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
7:34:00 PM WARN  user       Failed 'flow_path.flush()' database method (id=e086d55f)
FlushError: canceling statement due to statement timeout
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:813:31
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:804:21
    at HeadlessKysely.wrap (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/database/kysely.ts:58:24)
    at async Promise.all (index 26)

7:34:00 PM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
7:34:00 PM WARN  user       Failed 'flow_path.flush()' database method (id=d45c7898)
FlushError: canceling statement due to statement timeout
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:813:31
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:804:21
    at HeadlessKysely.wrap (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/database/kysely.ts:58:24)
    at async Promise.all (index 23)

7:34:00 PM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
7:34:00 PM WARN  user       Failed 'flow_path.flush()' database method (id=91652fb4)
FlushError: canceling statement due to statement timeout
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:813:31
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:804:21
    at HeadlessKysely.wrap (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/database/kysely.ts:58:24)
    at async Promise.all (index 30)

7:34:00 PM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
7:34:00 PM WARN  user       Failed 'flow_path.flush()' database method (id=40bc2801)
FlushError: canceling statement due to statement timeout
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:813:31
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:804:21
    at HeadlessKysely.wrap (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/database/kysely.ts:58:24)
    at async Promise.all (index 24)

7:34:00 PM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
7:34:00 PM WARN  user       Failed 'flow_path.flush()' database method (id=af9cc1da)
FlushError: canceling statement due to statement timeout
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:813:31
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:804:21
    at HeadlessKysely.wrap (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/database/kysely.ts:58:24)
    at async Promise.all (index 28)

7:34:00 PM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
7:34:00 PM WARN  user       Failed 'flow_path.flush()' database method (id=196f0633)
FlushError: canceling statement due to statement timeout
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:813:31
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:804:21
    at HeadlessKysely.wrap (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/database/kysely.ts:58:24)
    at async Promise.all (index 25)

7:34:00 PM ERROR indexing   Internal error occurred while flushing cache. Please report this error here: https://github.com/ponder-sh/ponder/issues
7:34:00 PM WARN  user       Failed 'flow_path.flush()' database method (id=08773e50)
FlushError: canceling statement due to statement timeout
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:813:31
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/indexing-store/historical.ts:804:21
    at HeadlessKysely.wrap (file:///Users/[userName]/Develop/ponder-token/token/node_modules/.pnpm/ponder@0.8.32_@opentelemetry+api@1.9.0_@types+node@20.17.16_hono@4.6.18_typescript@5.7.3_viem@2.22.14_typescript@5.7.3_/node_modules/ponder/src/database/kysely.ts:58:24)
    at async Promise.all (index 27)

### Expected behavior

_No response_

### Steps to reproduce

_No response_

### Link to repository

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kyscott18**
Closes #1469

### CODE REVIEW

File: packages/core/src/indexing-store/cache.ts [hunk 1]
```diff
@@ -225,6 +232,60 @@ const getBytes = (value: unknown) => {
...
+      if (value === null || value === undefined) {
+        result += "\\N";
+      } else {
+        if (column.mapToDriverValue !== undefined) {
+          value = column.mapToDriverValue(value);
+        }
+        if (value === null || value === undefined) {
+          result += "\\N";
+        } else {
+          result += String(value).replace(/\\/g, "\\\\");
```
Comment (kyscott18) [inline packages/core/src/indexing-store/cache.ts:256]: Do an array join

File: packages/core/src/indexing-store/cache.ts [hunk 2]
```diff
@@ -416,45 +482,61 @@ export const createIndexingCache = ({
             });
           }
           insertBuffer.get(table)!.clear();
-
-          common.logger.debug({
-            service: "database",
-            msg: `Inserted ${insertValues.length} '${getTableName(table)}' rows`,
-          });
```
Comment (typedarray) [inline packages/core/src/indexing-store/cache.ts:423]: I think this unintentionally reverts the logs I changed

File: packages/core/src/indexing-store/cache.ts [hunk 3]
```diff
@@ -379,32 +440,37 @@ export const createIndexingCache = ({
...
-            );
-          }
+          common.logger.debug({
+            service: "indexing",
+            msg: `Inserting ${insertValues.length} cached '${getTableName(table)}' rows into the database`,
+          });
+
+          const text = getCopyText(
+            table,
+            insertValues.map(({ row }) => row),
```
Comment (typedarray) [inline packages/core/src/indexing-store/cache.ts:464]: Didn't we have to be careful last time about memory here, to make sure the insertValues are garbage-collectable as we build the text?

File: packages/core/src/bin/utils/run.ts [hunk 4]
```diff
@@ -115,36 +115,43 @@ export async function run({
...
-      schemaBuild,
-      database,
-      indexingCache,
-      db: database.qb.drizzle,
-    });
-    const result = await indexing.processSetupEvents({
-      db: historicalIndexingStore,
-    });
+    await database.retry(async () => {
+      await database.transaction(async (client, tx) => {
```
[the remark this answers is not in the document]
Comment (kyscott18) [reply packages/core/src/bin/utils/run.ts:119]: Not really an oversight, it just wasn't necessary

File: packages/core/src/indexing-store/cache.ts (hunk 3 above)
Comment (kyscott18) [reply packages/core/src/indexing-store/cache.ts:464]: Previously, yes. That was when we were handling a cache that was too large and flushing buffer entries to the database at the same step. Now because the buffer entries get flushed in smaller and more frequent chunks it isn't necessary.

File: packages/core/src/indexing-store/cache.ts [hunk 5]
```diff
@@ -233,6 +241,57 @@ const getBytes = (value: unknown) => {
...
+          values.push("\\N");
+        } else {
+          values.push(String(value).replace(/\\/g, "\\\\"));
+        }
+      }
+    }
+    results.push(values.join("\t"));
+  }
+  return results.join("\n");
+};
```
Comment (kyscott18) [inline packages/core/src/indexing-store/cache.ts:270]: @typedarray Is this what you had in mind?

Comment (typedarray) [reply packages/core/src/indexing-store/cache.ts:270]: Yup LGTM
