### PR TITLE
fix: #1022

### LINKED ISSUE #1022: cli eta column format
The ETA column moves around a lot while syncing.

https://github.com/user-attachments/assets/b007b93b-6ddc-4329-8764-4bd0f6eaf661

Prefixing single digit minutes and seconds helps prevent it from shifting.

https://github.com/user-attachments/assets/b9e80bf6-be0f-49ee-92c7-844ad7a8abd5

Happy to open a PR to prefix these single digits. You are also welcome to close this issue if it's no big deal.

### PR DESCRIPTION
**Pull request by tmm**
Fixes #1022

### CODE REVIEW

File: packages/core/src/utils/format.ts [hunk 1]
```diff
@@ -8,8 +8,8 @@ export const formatEta = (ms: number) => {
   const s = seconds - h * 3600 - m * 60;
 
   const hstr = h > 0 ? `${h}h ` : "";
-  const mstr = m > 0 || h > 0 ? `${m}m ` : "";
-  const sstr = s > 0 || m > 0 ? `${s}s` : "";
+  const mstr = m > 0 || h > 0 ? `${m < 10 ? "0" : ""}${m}m ` : "";
```
Comment (tmm) [inline packages/core/src/utils/format.ts:11]: might only be worth prefixing if `h > 0`

```suggestion
  const mstr = m > 0 || h > 0 ? `${m < 10 && h > 0 ? "0" : ""}${m}m ` : "";
```

File: packages/core/src/utils/format.ts [hunk 2]
```diff
@@ -8,8 +8,8 @@ export const formatEta = (ms: number) => {
...
+  const sstr = s > 0 || m > 0 ? `${s < 10 ? "0" : ""}${s}s` : "";
```
Comment (tmm) [inline packages/core/src/utils/format.ts:12]: might only be worth prefixing if `m > 0`

```suggestion
  const sstr = s > 0 || m > 0 ? `${s < 10 && m > 0 ? "0" : ""}${s}s` : "";
```

File: packages/core/src/utils/format.ts
Comment (tmm) [inline packages/core/src/utils/format.ts:1]: could also add a space ` ` instead of a `0` since it will take up the same width 🤷‍♂️

File: packages/core/src/utils/format.ts (hunk 1 above)
Comment (0xOlias) [reply packages/core/src/utils/format.ts]: Yea I think it looks better without the leading zero.

before
```
│     ETA │
┼─────────┤
│ 03m 08s │
```

after
```
│     ETA │
┼─────────┤
│  3m 08s │
```

File: packages/core/src/utils/format.ts
Comment (0xOlias) [reply packages/core/src/utils/format.ts:1]: Tried it - I think `0` looks better!

**Review by 0xOlias — APPROVED** [review]
LGTM, confirmed locally
